(() => {
  /* injection guard — the popup can inject us into already-open tabs
     (so you never need F5); this stops double-initialization */
  if (window.__gslVaultInjected) return;
  window.__gslVaultInjected = true;

  /* SELF-SUFFICIENT: works even if shared.js isn't loaded first */
  const shared = globalThis.CollectorShared || {};
  const IMGRES_PREFIX = shared.IMGRES_PREFIX || 'https://www.google.com/imgres?q=';
  const normalizeUrl = shared.normalizeUrl || ((raw) => {
    try {
      const u = new URL(raw);
      u.searchParams.delete('ved');
      u.searchParams.delete('vet');
      u.hash = '';
      const params = [...u.searchParams.entries()].sort(([a], [b]) => a.localeCompare(b));
      return `${u.origin}${u.pathname}?${new URLSearchParams(params).toString()}`;
    } catch {
      return raw;
    }
  });

  const isGoogle = location.hostname.includes('google');

  let collecting = false;
  let autoCaptureInterval = null;
  let mutationTimer = null;
  let highlightTimer = null;

  /* highlight-collected state */
  let highlightEnabled = false;
  let collectedUrls = new Set();
  let collectedTbnids = new Set();
  let collectedImgs = new Set();

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  const getBoolSetting = (key, defaultValue) =>
    new Promise((resolve) => {
      chrome.storage.local.get([key], (res) => {
        resolve(typeof res[key] === 'boolean' ? res[key] : defaultValue);
      });
    });

  /* the one tile selector the outline AND the hover scan both key off */
  const TILE_SELECTOR = '[jsname="dTDiAc"][data-docid]';
  const SKIP_AREAS = '[role="dialog"], [role="menu"], [role="listbox"], g-dialog, #topstuff, #searchform, #botstuff, form';

  /* ---------------- simulated mouse ----------------
     Every result tile shares this skeleton (verified against real tiles):
       [jsname="dTDiAc"][data-docid]       result container
       [jsname="qQjpJ"][data-img-wrapper]  image wrapper
       a                                   imgres link — EMPTY until hovered
       [jscontroller="aw2uhd"] (.DeNS1c / [jsname="G3m5s"], id="e-<tbnid>")
                                           hover core — mouseover:UI3Kjd lives
                                           here; it's what writes the link
       [jsname="PNoEC"] (.RmwKgd)          aspect-ratio button
       .bFtXbb ([data-bla])                img shell
       img                                 thumbnail
     For each tile we walk the whole chain outer→inner with a realistic
     cursor (true center coordinates on every element). */
  const HOVER_CHAIN = [
    '[jsname="qQjpJ"], [data-img-wrapper]',
    'a',
    '[jscontroller="aw2uhd"], .DeNS1c, [jsname="G3m5s"]',
    '[jsname="PNoEC"], .RmwKgd',
    '.bFtXbb, [data-bla]',
    'img'
  ];

  function simulateMouse(el) {
    try {
      const r = el.getBoundingClientRect();
      const x = Math.round(r.left + r.width / 2);
      const y = Math.round(r.top + r.height / 2);
      const base = {
        bubbles: true, cancelable: true, view: window,
        clientX: x, clientY: y, screenX: x, screenY: y, button: 0
      };
      el.dispatchEvent(new PointerEvent('pointerover', base));
      el.dispatchEvent(new PointerEvent('pointerenter', { ...base, bubbles: false }));
      el.dispatchEvent(new MouseEvent('mouseover', base));
      el.dispatchEvent(new MouseEvent('mouseenter', { ...base, bubbles: false }));
      el.dispatchEvent(new MouseEvent('mousemove', base));
    } catch {}
  }

  function glanceTile(tile) {
    simulateMouse(tile);
    for (const sel of HOVER_CHAIN) {
      const el = tile.querySelector(sel);
      if (el) simulateMouse(el);
    }
  }

  function inViewport(el) {
    const r = el.getBoundingClientRect();
    const vh = window.innerHeight || 800;
    /* widened margin: pre-glance tiles just off-screen so their links
       are already generated by the time you scroll to them */
    return r.width > 0 && r.bottom > -300 && r.top < vh + 300;
  }

  function isUserTyping() {
    const ae = document.activeElement;
    return !!ae && (ae.tagName === 'INPUT' || ae.tagName === 'TEXTAREA' || ae.isContentEditable);
  }

  async function scanGoogle() {
    const hoverEnabled = await getBoolSetting('hover_enabled', true);
    const filterTolns = await getBoolSetting('filter_tolns', false);

    if (hoverEnabled && !isUserTyping()) {
      let glanced = 0;
      for (const tile of document.querySelectorAll(TILE_SELECTOR)) {
        if (glanced >= 60) break;
        if (tile.closest(SKIP_AREAS)) continue;
        if (!inViewport(tile)) continue;
        glanceTile(tile);
        glanced++;
      }
      if (glanced) await sleep(300);
    }

    const found = new Map();
    document.querySelectorAll('a[href]').forEach((a) => {
      if (!a.href.startsWith(IMGRES_PREFIX)) return;
      if (filterTolns && !a.closest('[data-tolns]')) return;
      const n = normalizeUrl(a.href);
      if (!found.has(n)) {
        /* extract title from parent tile */
        const tile = a.closest(TILE_SELECTOR);
        let title = '';
        if (tile) {
          const titleEl = tile.querySelector('.Q6A6Dc, [data-snippet], .VYhLad span');
          if (titleEl) title = titleEl.textContent.trim();
        }
        found.set(n, { href: a.href, title });
      }
    });
    return [...found.values()].map((v) => ({ url: v.href, title: v.title }));
  }

  /* generic mode: any page's images (min 150px, no svg/icons) */
  function scanGeneric() {
    const seen = new Set();
    const out = [];
    document.querySelectorAll('img').forEach((img) => {
      const src = img.currentSrc || img.src;
      if (!src || !/^https?:/.test(src)) return;
      if (/\.svg(\?|$)/i.test(src)) return;
      const w = img.naturalWidth || parseInt(img.getAttribute('width'), 10) || 0;
      const h = img.naturalHeight || parseInt(img.getAttribute('height'), 10) || 0;
      if (w && w < 150) return;
      if (h && h < 150) return;
      if (seen.has(src)) return;
      seen.add(src);
      out.push(src);
    });
    return out;
  }

  async function collectOnce() {
    if (collecting) return;
    collecting = true;
    try {
      if (isGoogle) {
        const results = await scanGoogle();
        const urls = results.map((r) => r.url);
        const titlesMap = new Map(results.map((r) => [r.url, r.title]));
        try { 
          await chrome.runtime.sendMessage({ 
            type: 'save_urls', 
            urls,
            titles: Object.fromEntries(titlesMap)
          }); 
        } catch {}
      } else {
        const images = scanGeneric();
        if (images.length) {
          try {
            await chrome.runtime.sendMessage({ type: 'save_generic', pageUrl: location.href, images });
          } catch {}
        }
      }
    } catch {}
    finally { collecting = false; }
  }

  /* ---------------- highlight collected items ---------------- */

  /* data-docid on each result tile === the tbnid param in the saved imgres URL */
  function extractTbnid(googleUrl) {
    try {
      return new URL(googleUrl).searchParams.get('tbnid') || '';
    } catch {
      return '';
    }
  }

  async function rebuildHighlightSets() {
    const res = await chrome.storage.local.get(['collected_items']);
    const items = Array.isArray(res.collected_items) ? res.collected_items : [];
    collectedUrls = new Set(items.map((i) => normalizeUrl(i.url)));
    collectedTbnids = new Set(items.map((i) => extractTbnid(i.url)).filter(Boolean));
    collectedImgs = new Set(items.map((i) => i.directImage).filter(Boolean));
  }

  function applyHighlight() {
    if (!highlightEnabled) return;

    if (isGoogle) {
      document.querySelectorAll(TILE_SELECTOR).forEach((tile) => {
        const docid = tile.getAttribute('data-docid');
        let match = collectedTbnids.has(docid);
        if (!match) {
          const a = tile.querySelector('a[href]');
          match = !!a && a.href.startsWith(IMGRES_PREFIX) && collectedUrls.has(normalizeUrl(a.href));
        }
        tile.classList.toggle('gsl-collected', match);
      });

      /* fallback for older Google layouts: mark outward from the imgres link */
      document.querySelectorAll('a[href]').forEach((a) => {
        if (!a.href.startsWith(IMGRES_PREFIX)) return;
        if (!collectedUrls.has(normalizeUrl(a.href))) return;
        const tile = a.closest(TILE_SELECTOR) || a.closest('[jscontroller="VQlOid"]') || a;
        tile.classList.add('gsl-collected');
      });
    } else {
      document.querySelectorAll('img').forEach((img) => {
        const src = img.currentSrc || img.src;
        img.classList.toggle('gsl-collected', collectedImgs.has(src));
      });
    }
  }

  function clearHighlight() {
    document.querySelectorAll('.gsl-collected').forEach((el) => el.classList.remove('gsl-collected'));
  }

  async function setHighlight(enabled) {
    highlightEnabled = enabled;
    if (enabled) {
      await rebuildHighlightSets();
      applyHighlight();
    } else {
      clearHighlight();
    }
  }

  /* instant sync: react to storage changes directly */
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== 'local') return;
    if (changes.highlight_collected) {
      setHighlight(!!changes.highlight_collected.newValue);
    }
    if (changes.auto_capture_enabled) {
      if (changes.auto_capture_enabled.newValue) startAutoCapture();
      else stopAutoCapture();
    }
    if (changes.collected_items && highlightEnabled) {
      rebuildHighlightSets().then(applyHighlight);
    }
  });

  /* ---------------- floating button + auto-capture ---------------- */

  function updateButton() {
    const btn = document.querySelector('.gsl-floating-btn');
    if (!btn) return;
    if (autoCaptureInterval) {
      btn.classList.add('auto-active');
      btn.textContent = 'Auto capturing...';
    } else {
      btn.classList.remove('auto-active');
      btn.textContent = isGoogle ? 'Collect image links' : 'Collect page images';
    }
  }

  function startAutoCapture() {
    if (autoCaptureInterval) return;
    collectOnce();
    autoCaptureInterval = setInterval(collectOnce, 1000);
    updateButton();
  }

  function stopAutoCapture() {
    if (!autoCaptureInterval) return;
    clearInterval(autoCaptureInterval);
    autoCaptureInterval = null;
    updateButton();
  }

  async function initAutoCapture() {
    const enabled = await getBoolSetting('auto_capture_enabled', false);
    if (enabled) startAutoCapture();
    else stopAutoCapture();
  }

  const style = document.createElement('style');
  style.textContent = `
    .gsl-floating-btn { position: fixed; right: 12px; bottom: 12px; z-index: 2147483647; background: #4285f4; color: #fff; padding: 8px 10px; border-radius: 6px; cursor: pointer; font: 13px Arial; box-shadow: 0 2px 6px rgba(0,0,0,0.3); }
    .gsl-floating-btn:hover { background: #3367d6; }
    .gsl-floating-btn.auto-active { background: #34a853; animation: gsl-pulse 2s infinite; }
    @keyframes gsl-pulse { 0% { box-shadow: 0 0 0 0 rgba(52,168,83,0.4); } 70% { box-shadow: 0 0 0 10px rgba(52,168,83,0); } 100% { box-shadow: 0 0 0 0 rgba(52,168,83,0); } }

    .gsl-collected { position: relative; outline: 3px solid #2ecc71 !important; outline-offset: 1px; animation: gsl-glow 2.6s ease-in-out infinite; }
    .gsl-collected::after { content: '✓'; position: absolute; top: -6px; right: -6px; width: 18px; height: 18px; background: #2ecc71; color: #06341b; border-radius: 50%; font: 700 11px/18px Arial; text-align: center; box-shadow: 0 1px 5px rgba(0,0,0,.45); z-index: 2147483647; pointer-events: none; }
    @keyframes gsl-glow {
      0%, 100% { box-shadow: 0 0 0 4px rgba(46,204,113,.16), 0 0 12px rgba(46,204,113,.35); }
      50% { box-shadow: 0 0 0 6px rgba(46,204,113,.3), 0 0 22px rgba(46,204,113,.6); }
    }
  `;
  document.head.appendChild(style);

  /* remove any stale button from a previously injected version */
  document.querySelectorAll('.gsl-floating-btn').forEach((b) => b.remove());

  const btn = document.createElement('div');
  btn.className = 'gsl-floating-btn';
  btn.onclick = collectOnce;
  document.body.appendChild(btn);

  /* outlines refresh on a short 80ms fuse, fully decoupled from collecting */
  new MutationObserver(() => {
    if (highlightEnabled) {
      clearTimeout(highlightTimer);
      highlightTimer = setTimeout(applyHighlight, 80);
    }
    clearTimeout(mutationTimer);
    mutationTimer = setTimeout(collectOnce, 250);
  }).observe(document.documentElement, { childList: true, subtree: true });

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || !msg.type) return;

    if (msg.type === 'ping') {
      sendResponse({ ok: true });
      return;
    }

    if (msg.type === 'request_page_urls') {
      if (isGoogle) {
        scanGoogle()
          .then((urls) => sendResponse({ urls }))
          .catch(() => sendResponse({ urls: [] }));
      } else {
        try {
          sendResponse({ images: scanGeneric(), pageUrl: location.href });
        } catch {
          sendResponse({ images: [], pageUrl: location.href });
        }
      }
      return true;
    }

    if (msg.type === 'toggle_auto_capture') {
      if (msg.enabled) startAutoCapture();
      else stopAutoCapture();
      sendResponse({ ok: true });
    }

    if (msg.type === 'toggle_highlight') {
      setHighlight(!!msg.enabled);
      sendResponse({ ok: true });
    }
  });

  /* boot: restore persisted state on EVERY load — new tab, F5, navigation */
  initAutoCapture();
  collectOnce();
  getBoolSetting('highlight_collected', false).then((on) => {
    if (on) setHighlight(true);
  });

  requestAnimationFrame(updateButton);
})();